# Generated by Django 5.1.5 on 2025-01-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_added',
        ),
    ]
