# Generated by Django 5.1.5 on 2025-01-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_rename_blogpost_post_rename_date_post_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='BlogPost',
        ),
    ]
